name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=assets/game_icon.ico xo_game_styled.py --name "XO_Styled"
          dir dist || ls -la dist

      - name: Upload built exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: XO_Styled_windows_exe
          path: dist/XO_Styled.exe
